### ISSUE TITLE
能否支持if 和表格循环？

### ISSUE THREAD

**Issue by xwinie** [lukasjarosch/go-docx#6]
能否支持if 和表格循环？

**Comment by lukasjarosch** [comment]
Sorry, please write english

**Comment by extbe** [comment]
Hi. I guess this is a feature request to support iteration over arrays and conditional rendering (`if` statement). It would be nice to be able to generate table rows based on some array of structs :)

**Comment by lukasjarosch** [comment]
Hey, sorry for getting back so late. I'm not really monitoring this repo anymore.

I've experimented with conditional rendering as well as insertion of new data. 
But implementing this would be very complex since the project's aim is **not** to project the WordprocessingML spec into a Go-struct. It is meant to work on the raw bytes of the document.

Thus injecting new XML structs is somewhat out-of scope, sorry.

There is one project on github which is aimed at such use-cases: https://github.com/unidoc/unioffice 
Unfortunately that project is not free of charge, which is why I've developed this library for my specific use-case.

But if you want to introduce that feature into this lib, I'm happily accepting PRs :)
