### ISSUE TITLE
Many paragraphs.

### ISSUE THREAD

**Issue by mantoze** [lukasjarosch/go-docx#7]
Hi,
Is it possible to replace the placeholder with array of strings, where each array member would be in a new paragraph? Maybe it's possible to do it some other way?
If so, maybe you can give an example.

**Comment by lukasjarosch** [comment]
Hey, this would mean to dynamically inject xml into the document while iterating over the array. Unfortunately this is not possible because there is no internal xml representation which would be required to insert elements.

I would love to have helped you with your issue. Unfortunately I don't have that much spare time to implement this kind of feature.

Feel free to give it a shot, tho :grinning:
