### ISSUE TITLE
Is it possible to avoid line break collapse?

### ISSUE THREAD

**Issue by jordanconway** [lukasjarosch/go-docx#8]
Hello,
I'm trying to use a value that's a literal string with some line breaks in it. Currently the line breaks gets collapsed and the string no longer looks the way I expect it to. 

```
docx.PlaceholderMap{
   "PLACEHOLDER_KEY":    `here is my string
with different 
items on 
multiple lines
`,
}
```
turns into 
` here is my string with different items on multiple lines `

Is it possible to preserve line breaks in placeholder values?

**Comment by lukasjarosch** [comment]
Hey, 
at the moment this is not possible. The reason this happens is because go-docx will put the value inside the first text-run (`<w:t>`) of the found placeholder.

Given the following fragments which define the `{key_with_underscore}` placeholder:
```xml
<w:r>
  <w:rPr>
    <w:b/>
    <w:highlight w:val="yellow"/>
    <w:bCs/>
  </w:rPr>
  <w:t>{key_</w:t>
</w:r>
<w:r>
  <w:rPr>
    <w:b/>
    <w:highlight w:val="yellow"/>
    <w:bCs/>
    <w:sz w:val="32"/>
    <w:szCs w:val="32"/>
  </w:rPr>
  <w:t>with</w:t>
</w:r>
<w:r>
  <w:rPr>
    <w:b/>
    <w:highlight w:val="yellow"/>
    <w:bCs/>
  </w:rPr>
  <w:t>_underscore}</w:t>
</w:r>
```

All but the first fragment (`<w:r>`) is stripped and the text inside the first fragment is replaced with your value.
The resulting xml looks like that:
```xml
<w:r>
  <w:rPr>
    <w:b/>
    <w:highlight w:val="yellow"/>
    <w:bCs/>
  </w:rPr>
  <w:t>here is my string with different items on multiple lines
</w:t>
</w:r>
```


In order to add a line-break, according to the [spec](http://officeopenxml.com/WPtextSpecialContent-break.php), one would have to insert new XML text elements. The resulting xml might need to look something like this

```xml
<w:r>
  <w:rPr>
    <w:b/>
    <w:bCs/>
  </w:rPr>
  <w:t>here is my string</w:t>
  <w:br/>
  <w:t xml:space="preserve">with different</w:t>
  <w:br/>
  <w:t xml:space="preserve">items on</w:t>
  <w:br/>
  <w:t xml:space="preserve">multiple lines</w:t>
</w:r>
```
As mentioned in #3, adding XML is out of scope for this project, especially since I do not have much time to work on it at the moment. So if you need to have line-breaks, your best option currently is to use multiple placeholders for the separate lines.
If you want to give an implementation a try, PRs are welcome 😃

**Comment by jordanconway** [comment]
Thanks for the context!
